language: java
install: true

jdk:
  - oraclejdk8
  - oraclejdk11
 
stages:
- name: build
- name: snapshot
  if: branch = development AND type = push
- name: release
  if: branch = master AND type = push

jobs:
  include:
  - stage: build
    script: ./gradlew skema:build
  - stage: snapshot
    script: ./gradlew skema:artifactoryPublish --exclude-task test -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}
  - stage: release
    script: ./gradlew skema:bintrayUpload --exclude-task test -Drelease=true -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}

deploy:
  provider: releases
  api_key: ${ACCESS_TOKEN}
  skip_cleanup: true
  file: skema/build/libs/skema-${TRAVIS_TAG}.jar
  on:
    repo: hhu-bsinfo/skema
    branch: master
    tags: true
